#name : throw Exception
# key: exc
# --
throw new ${1:Type}Exception($2);